chore: delete player.png:Zone.Identifier (#149)
This file breaks cloning in Windows OS:
```
git.exe checkout --no-track -b myBranch remotes/VUERO/main --
error: invalid path 'public/demo/photos/soccer/player.png:Zone.Identifier'
```